name: Update Eternity.yml

on:
  schedule:
    - cron: '0 * * * *'  # раз в час
  workflow_dispatch:       # позволяет запускать вручную

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}  # Используем секрет с твоим PAT

    - name: Download Eternity.yml from V2RayAggregator
      run: |
        curl -L -o Eternity.yml https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.yml

    - name: Commit changes if any
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Eternity.yml
        git diff-index --quiet HEAD || git commit -m "Update Eternity.yml from V2RayAggregator"

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
